#!/bin/bash

RED="\e[0;31m"
GREEN="\e[0;32m"
RESET="\e[0m"

log() {
    echo -ne "${GREEN}log${RESET} | $1\n"
}

error() {
    echo -ne "${RED}error${RESET} | $1\n"
    exit 1
}

build() {
    RUSTFLAGS="-Awarnings" cargo build || error "build error caught."
}

test() {
    cargo test || error "test error caught."
}

run() {
    if [[ ! -f ./target/debug/koshka2 ]]; then 
        error "couldn't find the Koshka II RS binary. run \"./ball -build\" first."
    fi
    ./target/debug/koshka2
}

clean() {
    rm -rf target/
}

help() {
    echo "Usage: ./ball [OPTIONS]"
    echo "Options:"
    echo "  -build             Build the project"
    echo "  -test              Run tests"
    echo "  -run               Run the emulator"
    echo "  -full              Do everything (clean + build + test + run)"
    echo "  -clean             Remove the target/ directory"
    echo "  -h, --help         Show this help"
    exit 0
}

for arg in "$@"; do
    case $arg in
        -build) build | tee ball.log ;;
        -test) test | tee ball.log ;;
        -run) run | tee ball.log;;
        -full) clean && test && build && run | tee ball.log ;;
        -h|-help) help  ;;
        -clean) clean  ;;
        *)
            error "Unknown option: $arg. Use -h for help."
            ;;
    esac
done



if [[ $# -eq 0 ]]; then
    error "No arguments provided. Use -h for help."
fi
